# Gear Master — shortcuts.
#
#   make              play the game (same as `make gearmaster`)
#   make help         list every command
#
# Lines beginning with `## name: text` below are what `make help` prints.

CARGO ?= cargo
GUI   := gearmaster-gui
CLI   := gearmaster-cli

# Absolute path to this directory, so `make install`'s launcher works from
# anywhere the user happens to be.
ROOT   := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
PREFIX ?= $(HOME)/.local
BINDIR := $(PREFIX)/bin
BIN    := $(BINDIR)/gearmaster

.DEFAULT_GOAL := gearmaster
.PHONY: gearmaster play run release geared cli pack test build check clean help install uninstall \
        package package-macos package-windows package-web web serve publish icon

## gearmaster: build if needed, then play
gearmaster:
	@$(CARGO) run -p $(GUI)

# Aliases, for whichever word you reach for.
play run: gearmaster

## release: play an optimised build (slower to compile, smoother to run)
release:
	@$(CARGO) run --release -p $(GUI)

## geared: play with every slot pre-filled, to skip straight to a fight
geared:
	@GEARMASTER_PRESET=1 $(CARGO) run -p $(GUI)

## pack: dress creatures by hand - the game, editing somebody else's board
pack:
	@GEARMASTER_PACK=1 $(CARGO) run -p $(GUI)

## cli: play headlessly in the terminal
cli:
	@$(CARGO) run -q -p $(CLI)

## test: run the whole suite (59 tests, no window needed)
test:
	@$(CARGO) test

## build: compile everything without running it
build:
	@$(CARGO) build

## check: fast type-check, no binaries produced
check:
	@$(CARGO) check --workspace --all-targets

## package: build a shareable macOS app (dist/GearMaster-macOS.zip)
package package-macos:
	@$(ROOT)/packaging/package-macos.sh

## package-windows: cross-compile a Windows .exe (needs mingw-w64)
package-windows:
	@$(ROOT)/packaging/package-windows.sh

## web: build the browser version (dist/web + GearMaster-Web.zip)
web package-web:
	@$(ROOT)/packaging/package-web.sh

## serve: build the browser version and open it locally
serve: web
	@echo "Serving http://localhost:8080/ - Ctrl-C to stop"
	@(sleep 1 && open http://localhost:8080/) >/dev/null 2>&1 &
	@cd $(ROOT)/dist/web && python3 -m http.server 8080

## publish: rebuild the web version into docs/ and push it to GitHub Pages
publish: web
	@cp $(ROOT)/dist/web/* $(ROOT)/docs/
	@touch $(ROOT)/docs/.nojekyll
	@cd $(ROOT) && git add docs && \
	  (git diff --cached --quiet && echo "docs/ unchanged - nothing to publish" \
	   || (git commit -q -m "Publish web build" && git push -q && \
	       echo "Pushed. Pages redeploys in about a minute."))

## icon: regenerate the app icon from scratch
icon:
	@python3 $(ROOT)/packaging/make-icon.py

## clean: delete build artifacts and packaged output
clean:
	@$(CARGO) clean
	@rm -rf $(ROOT)/dist

## install: put a standalone `gearmaster` command in ~/.local/bin
install:
	@$(CARGO) build --release -p $(GUI)
	@mkdir -p $(BINDIR)
	@printf '#!/bin/sh\n# Generated by the Gear Master Makefile.\nexec %s run --release --quiet --manifest-path "%s/Cargo.toml" -p %s "$$@"\n' \
	  '$(CARGO)' '$(ROOT)' '$(GUI)' > $(BIN)
	@chmod +x $(BIN)
	@echo "Installed $(BIN)"
	@case ":$$PATH:" in \
	  *":$(BINDIR):"*) echo "Run it with: gearmaster" ;; \
	  *) echo "$(BINDIR) is not on your PATH. Add it, or run $(BIN) directly." ;; \
	esac

## uninstall: remove that command again
uninstall:
	@rm -f $(BIN) && echo "Removed $(BIN)"

## help: list these commands
help:
	@echo "Gear Master"
	@echo
	@grep -E '^## [a-z]' $(MAKEFILE_LIST) | sed 's/^## //' \
	  | awk -F': ' '{ printf "  make %-16s %s\n", $$1, $$2 }'
	@echo
	@echo "  In game: drag pieces into slots, right-click to rotate,"
	@echo "           then press BEGIN FIGHT."
